"""Deterministic calculation engine for one-lot low-bid justifications."""

from .calculations import (
    calculate_generated_unit_cost,
    calculate_justification,
    canonical_decimal,
    economic_payload,
    factor_for_percentage,
    format_spanish_amount,
    format_spanish_percentage_points,
    format_spanish_ratio_percentage,
    format_spanish_unit_cost,
    round_half_up,
)
from .cost_generation import (
    RandomIntegerSource,
    RandomSource,
    generate_initial_costs,
    recalculate_products,
    remove_manual_cost,
    set_manual_cost,
    set_product_lock,
)
from .domain import (
    CalculationResult,
    CostActionResult,
    CostOrigin,
    CostRange,
    DomainValueError,
    EconomicDisplay,
    EconomicValues,
    FinancialInput,
    IssueSeverity,
    Justification,
    Product,
    ProductLineDisplay,
    ProductLineResult,
    TransportInput,
    ValidationIssue,
    decimal_value,
)
from .snapshot import (
    CALCULATION_ALGORITHM_VERSION,
    SNAPSHOT_SCHEMA_VERSION,
    CanonicalSnapshot,
    SnapshotBuildResult,
    SnapshotLoadResult,
    SnapshotMetadata,
    create_snapshot,
    load_snapshot,
)
from .validations import validate_calculated_values, validate_justification


__all__ = (
    "CALCULATION_ALGORITHM_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "CalculationResult",
    "CanonicalSnapshot",
    "CostActionResult",
    "CostOrigin",
    "CostRange",
    "DomainValueError",
    "EconomicDisplay",
    "EconomicValues",
    "FinancialInput",
    "IssueSeverity",
    "Justification",
    "Product",
    "ProductLineDisplay",
    "ProductLineResult",
    "RandomIntegerSource",
    "RandomSource",
    "SnapshotBuildResult",
    "SnapshotLoadResult",
    "SnapshotMetadata",
    "TransportInput",
    "ValidationIssue",
    "calculate_generated_unit_cost",
    "calculate_justification",
    "canonical_decimal",
    "create_snapshot",
    "decimal_value",
    "economic_payload",
    "factor_for_percentage",
    "format_spanish_amount",
    "format_spanish_percentage_points",
    "format_spanish_ratio_percentage",
    "format_spanish_unit_cost",
    "generate_initial_costs",
    "load_snapshot",
    "recalculate_products",
    "remove_manual_cost",
    "round_half_up",
    "set_manual_cost",
    "set_product_lock",
    "validate_calculated_values",
    "validate_justification",
)
